apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub_rabbitmq
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: connectionString
    value: "amqp://guest:guest@host.docker.internal:5672"